db.pameldinger.insertMany(
  {
    _id: 1,
    arrangement_id: 1,
    medlem: {
      mId: 1002,
      fornavn: "Kari",
      etternavn: "Hansen",
      epost: "kari.hansen@example.com",
      telefon: "23456789",
    },
    pameldt_dato: "2026-05-10",
    status: "bekreftet",
  },
  {
    _id: 2,
    arrangement_id: 1,
    medlem: {
      mId: 1003,
      fornavn: "Ola",
      etternavn: "Nordmann",
      epost: "ola.nordmann@example.com",
      telefon: "34567890",
    },
    pameldt_dato: "2026-05-12",
    status: "bekreftet",
  },
  {
    _id: 3,
    arrangement_id: 1,
    medlem: {
      mId: 1005,
      fornavn: "Jonas",
      etternavn: "Berg",
      epost: "jonas.berg@example.com",
      telefon: "56789012",
    },
    pameldt_dato: "2026-05-15",
    status: "avmeldt",
  },
  {
    _id: 4,
    arrangement_id: 2,
    medlem: {
      mId: 1001,
      fornavn: "Lars",
      etternavn: "Jenssen",
      epost: "lars.jenssen@example.no",
      telefon: "12345678",
    },
    pameldt_dato: "2026-11-20",
    status: "bekreftet",
  },
  {
    _id: 5,
    arrangement_id: 2,
    medlem: {
      mId: 1007,
      fornavn: "Erik",
      etternavn: "Andersen",
      epost: "erik.andersen@example.com",
      telefon: "78901234",
    },
    pameldt_dato: "2026-11-22",
    status: "bekreftet",
  },
  {
    _id: 6,
    arrangement_id: 2,
    medlem: {
      mId: 1010,
      fornavn: "Marte",
      etternavn: "Saether",
      epost: "marte.saether@example.com",
      telefon: "01234567",
    },
    pameldt_dato: "2026-12-01",
    status: "avmeldt",
  },
);
